development:
  adapter: mysql2
  database: weekly_do_dev
  pool: 5
  host: localhost
  username: username
  password: password
test:
  adapter: mysql2
  database: weekly_do_test
  pool: 5
  host: localhost
  username: username
  password: password
